repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^lightrag/api/webui/
      - id: end-of-file-fixer
        exclude: ^lightrag/api/webui/
      - id: requirements-txt-fixer
        exclude: ^lightrag/api/webui/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-format
        exclude: ^lightrag/api/webui/
      - id: ruff
        args: [--fix, --ignore=E402]
        exclude: ^lightrag/api/webui/

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.50"
    hooks:
      - id: check-manifest
        stages: [manual]
        exclude: ^lightrag/api/webui/

  # Local hook to build and stage frontend before commit
  - repo: local
    hooks:
      - id: build-frontend-and-stage
        name: Build and Stage Frontend
        entry: |
          bash -c 'cd ../Augentik_FrontEnd && \
          npm install && \
          npm run build && \
          rm -rf ../LightRAG-3/lightrag/api/webui/* && \
          cp -r dist/* ../LightRAG-3/lightrag/api/webui/ && \
          cd ../LightRAG-3 && \
          git add lightrag/api/webui'
        language: system
        pass_filenames: false
