CREATE EXTENSION IF NOT EXISTS vector;
CREATE DATABASE amd;

\c amd

CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS amd AUTHORIZATION CURRENT_USER;

CREATE ROLE amd_app LOGIN PASSWORD 'AppUser#25' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
GRANT USAGE ON SCHEMA amd TO amd_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA amd TO amd_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA amd TO amd_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA amd GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO amd_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA amd GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO amd_app;
